export {
  APP_SHOWCASE_SCENE_BEATS,
  APP_SHOWCASE_SCENE_COUNT,
  APP_SHOWCASE_STYLE,
  buildShowcaseJsonSchema as buildAppShowcaseJsonSchema,
  buildShowcaseSceneStructurePrompt as buildAppShowcaseSceneStructurePrompt,
  buildShowcaseSystemPrompt as buildAppShowcaseSystemPrompt,
  buildShowcaseUserPrompt as buildAppShowcaseUserPrompt,
  getMaxScenesForStyle,
  getMinScenesForStyle,
  getShowcaseBeatForIndex,
  isAppShowcaseStyle,
  PLATFORM_MODULES,
  SHOWCASE_WORKFLOW_BEATS,
  stylesRequiringMascot,
  type AppShowcaseGenerateInput,
  type AppShowcaseSceneBeat,
  type PlatformModule,
  type ShowcaseModuleBeat,
} from "@/lib/marketing/saas-showcase-engine"

export {
  APP_SHOWCASE_BASE_PATH,
  FITCORE_SHOWCASE_ASSETS,
  FITCORE_SHOWCASE_ASSET_KEYS,
  attachShowcaseAssetToScene,
  getShowcaseAsset,
  getShowcaseAssetForModule,
  getVideoSceneAssetFields,
  mapShowcaseAssetsToScenes,
  moduleToAssetKey,
  resolveShowcaseAssetForScene,
  type FitCoreShowcaseAsset,
  type FitCoreShowcaseAssetKey,
} from "@/lib/marketing/app-showcase-engine"
