import type { ContentPerformanceRow } from "@/lib/marketing/content-performance/types"

export const mockContentPerformanceRows: ContentPerformanceRow[] = [
  {
    id: "demo-cp-1",
    created_by: "demo-user",
    post_id: null,
    title: "3 gym mistakes killing your progress",
    platform: "TikTok",
    views: 12400,
    likes: 980,
    comments: 142,
    shares: 88,
    saves: 210,
    followers_gained: 47,
    content_type: "Educational",
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-cp-2",
    created_by: "demo-user",
    post_id: null,
    title: "High-protein meal prep in 20 minutes",
    platform: "Instagram",
    views: 5200,
    likes: 410,
    comments: 56,
    shares: 34,
    saves: 180,
    followers_gained: 22,
    content_type: "Nutrition",
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-cp-3",
    created_by: "demo-user",
    post_id: null,
    title: "Member transformation: 12 weeks",
    platform: "Instagram",
    views: 3875,
    likes: 290,
    comments: 48,
    shares: 22,
    saves: 95,
    followers_gained: 18,
    content_type: "Transformation",
    created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-cp-4",
    created_by: "demo-user",
    post_id: null,
    title: "Cardio before weights? Myth busted",
    platform: "Instagram",
    views: 2100,
    likes: 62,
    comments: 14,
    shares: 6,
    saves: 18,
    followers_gained: 3,
    content_type: "Educational",
    created_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-cp-5",
    created_by: "demo-user",
    post_id: null,
    title: "5-minute warm-up every lifter skips",
    platform: "TikTok",
    views: 8900,
    likes: 720,
    comments: 98,
    shares: 54,
    saves: 160,
    followers_gained: 31,
    content_type: "Workout",
    created_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
]
